/**
 * Liste complète des pays du monde (ISO 3166-1), noms en français.
 * Source unique pour le sélecteur de pays (checkout + onboarding — LOT A / QA T04).
 */

export interface Country {
  /** ISO 3166-1 alpha-2 (ex: "CI") */
  code: string
  /** Nom français */
  name: string
}

export const ALL_COUNTRIES: readonly Country[] = [
  { code: "AF", name: "Afghanistan" },
  { code: "ZA", name: "Afrique du Sud" },
  { code: "AL", name: "Albanie" },
  { code: "DZ", name: "Algérie" },
  { code: "DE", name: "Allemagne" },
  { code: "AD", name: "Andorre" },
  { code: "AO", name: "Angola" },
  { code: "AG", name: "Antigua-et-Barbuda" },
  { code: "SA", name: "Arabie saoudite" },
  { code: "AR", name: "Argentine" },
  { code: "AM", name: "Arménie" },
  { code: "AU", name: "Australie" },
  { code: "AT", name: "Autriche" },
  { code: "AZ", name: "Azerbaïdjan" },
  { code: "BS", name: "Bahamas" },
  { code: "BH", name: "Bahreïn" },
  { code: "BD", name: "Bangladesh" },
  { code: "BB", name: "Barbade" },
  { code: "BE", name: "Belgique" },
  { code: "BZ", name: "Belize" },
  { code: "BJ", name: "Bénin" },
  { code: "BT", name: "Bhoutan" },
  { code: "BY", name: "Biélorussie" },
  { code: "MM", name: "Birmanie (Myanmar)" },
  { code: "BO", name: "Bolivie" },
  { code: "BA", name: "Bosnie-Herzégovine" },
  { code: "BW", name: "Botswana" },
  { code: "BR", name: "Brésil" },
  { code: "BN", name: "Brunei" },
  { code: "BG", name: "Bulgarie" },
  { code: "BF", name: "Burkina Faso" },
  { code: "BI", name: "Burundi" },
  { code: "KH", name: "Cambodge" },
  { code: "CM", name: "Cameroun" },
  { code: "CA", name: "Canada" },
  { code: "CV", name: "Cap-Vert" },
  { code: "CL", name: "Chili" },
  { code: "CN", name: "Chine" },
  { code: "CY", name: "Chypre" },
  { code: "CO", name: "Colombie" },
  { code: "KM", name: "Comores" },
  { code: "CG", name: "Congo" },
  { code: "CD", name: "Congo (RDC)" },
  { code: "KR", name: "Corée du Sud" },
  { code: "KP", name: "Corée du Nord" },
  { code: "CR", name: "Costa Rica" },
  { code: "CI", name: "Côte d'Ivoire" },
  { code: "HR", name: "Croatie" },
  { code: "CU", name: "Cuba" },
  { code: "DK", name: "Danemark" },
  { code: "DJ", name: "Djibouti" },
  { code: "DM", name: "Dominique" },
  { code: "EG", name: "Égypte" },
  { code: "AE", name: "Émirats arabes unis" },
  { code: "EC", name: "Équateur" },
  { code: "ER", name: "Érythrée" },
  { code: "ES", name: "Espagne" },
  { code: "EE", name: "Estonie" },
  { code: "SZ", name: "Eswatini" },
  { code: "US", name: "États-Unis" },
  { code: "ET", name: "Éthiopie" },
  { code: "FJ", name: "Fidji" },
  { code: "FI", name: "Finlande" },
  { code: "FR", name: "France" },
  { code: "GA", name: "Gabon" },
  { code: "GM", name: "Gambie" },
  { code: "GE", name: "Géorgie" },
  { code: "GH", name: "Ghana" },
  { code: "GR", name: "Grèce" },
  { code: "GD", name: "Grenade" },
  { code: "GT", name: "Guatemala" },
  { code: "GN", name: "Guinée" },
  { code: "GQ", name: "Guinée équatoriale" },
  { code: "GW", name: "Guinée-Bissau" },
  { code: "GY", name: "Guyana" },
  { code: "HT", name: "Haïti" },
  { code: "HN", name: "Honduras" },
  { code: "HU", name: "Hongrie" },
  { code: "IN", name: "Inde" },
  { code: "ID", name: "Indonésie" },
  { code: "IQ", name: "Irak" },
  { code: "IR", name: "Iran" },
  { code: "IE", name: "Irlande" },
  { code: "IS", name: "Islande" },
  { code: "IL", name: "Israël" },
  { code: "IT", name: "Italie" },
  { code: "JM", name: "Jamaïque" },
  { code: "JP", name: "Japon" },
  { code: "JO", name: "Jordanie" },
  { code: "KZ", name: "Kazakhstan" },
  { code: "KE", name: "Kenya" },
  { code: "KG", name: "Kirghizistan" },
  { code: "KI", name: "Kiribati" },
  { code: "KW", name: "Koweït" },
  { code: "LA", name: "Laos" },
  { code: "LS", name: "Lesotho" },
  { code: "LV", name: "Lettonie" },
  { code: "LB", name: "Liban" },
  { code: "LR", name: "Liberia" },
  { code: "LY", name: "Libye" },
  { code: "LI", name: "Liechtenstein" },
  { code: "LT", name: "Lituanie" },
  { code: "LU", name: "Luxembourg" },
  { code: "MK", name: "Macédoine du Nord" },
  { code: "MG", name: "Madagascar" },
  { code: "MY", name: "Malaisie" },
  { code: "MW", name: "Malawi" },
  { code: "MV", name: "Maldives" },
  { code: "ML", name: "Mali" },
  { code: "MT", name: "Malte" },
  { code: "MA", name: "Maroc" },
  { code: "MH", name: "Îles Marshall" },
  { code: "MU", name: "Maurice" },
  { code: "MR", name: "Mauritanie" },
  { code: "MX", name: "Mexique" },
  { code: "FM", name: "Micronésie" },
  { code: "MD", name: "Moldavie" },
  { code: "MC", name: "Monaco" },
  { code: "MN", name: "Mongolie" },
  { code: "ME", name: "Monténégro" },
  { code: "MZ", name: "Mozambique" },
  { code: "NA", name: "Namibie" },
  { code: "NR", name: "Nauru" },
  { code: "NP", name: "Népal" },
  { code: "NI", name: "Nicaragua" },
  { code: "NE", name: "Niger" },
  { code: "NG", name: "Nigeria" },
  { code: "NO", name: "Norvège" },
  { code: "NZ", name: "Nouvelle-Zélande" },
  { code: "OM", name: "Oman" },
  { code: "UG", name: "Ouganda" },
  { code: "UZ", name: "Ouzbékistan" },
  { code: "PK", name: "Pakistan" },
  { code: "PW", name: "Palaos" },
  { code: "PS", name: "Palestine" },
  { code: "PA", name: "Panama" },
  { code: "PG", name: "Papouasie-Nouvelle-Guinée" },
  { code: "PY", name: "Paraguay" },
  { code: "NL", name: "Pays-Bas" },
  { code: "PE", name: "Pérou" },
  { code: "PH", name: "Philippines" },
  { code: "PL", name: "Pologne" },
  { code: "PT", name: "Portugal" },
  { code: "QA", name: "Qatar" },
  { code: "CF", name: "République centrafricaine" },
  { code: "DO", name: "République dominicaine" },
  { code: "CZ", name: "République tchèque" },
  { code: "RO", name: "Roumanie" },
  { code: "GB", name: "Royaume-Uni" },
  { code: "RU", name: "Russie" },
  { code: "RW", name: "Rwanda" },
  { code: "KN", name: "Saint-Christophe-et-Niévès" },
  { code: "SM", name: "Saint-Marin" },
  { code: "VC", name: "Saint-Vincent-et-les-Grenadines" },
  { code: "LC", name: "Sainte-Lucie" },
  { code: "SB", name: "Îles Salomon" },
  { code: "SV", name: "Salvador" },
  { code: "WS", name: "Samoa" },
  { code: "ST", name: "Sao Tomé-et-Principe" },
  { code: "SN", name: "Sénégal" },
  { code: "RS", name: "Serbie" },
  { code: "SC", name: "Seychelles" },
  { code: "SL", name: "Sierra Leone" },
  { code: "SG", name: "Singapour" },
  { code: "SK", name: "Slovaquie" },
  { code: "SI", name: "Slovénie" },
  { code: "SO", name: "Somalie" },
  { code: "SD", name: "Soudan" },
  { code: "SS", name: "Soudan du Sud" },
  { code: "LK", name: "Sri Lanka" },
  { code: "SE", name: "Suède" },
  { code: "CH", name: "Suisse" },
  { code: "SR", name: "Suriname" },
  { code: "SY", name: "Syrie" },
  { code: "TJ", name: "Tadjikistan" },
  { code: "TZ", name: "Tanzanie" },
  { code: "TD", name: "Tchad" },
  { code: "TH", name: "Thaïlande" },
  { code: "TL", name: "Timor oriental" },
  { code: "TG", name: "Togo" },
  { code: "TO", name: "Tonga" },
  { code: "TT", name: "Trinité-et-Tobago" },
  { code: "TN", name: "Tunisie" },
  { code: "TM", name: "Turkménistan" },
  { code: "TR", name: "Turquie" },
  { code: "TV", name: "Tuvalu" },
  { code: "UA", name: "Ukraine" },
  { code: "UY", name: "Uruguay" },
  { code: "VU", name: "Vanuatu" },
  { code: "VA", name: "Vatican" },
  { code: "VE", name: "Venezuela" },
  { code: "VN", name: "Vietnam" },
  { code: "YE", name: "Yémen" },
  { code: "ZM", name: "Zambie" },
  { code: "ZW", name: "Zimbabwe" },
] as const

/**
 * Indicatifs téléphoniques internationaux (sans le `+`) par code ISO 3166-1
 * alpha-2. Source pour le sélecteur d'indicatif à l'inscription.
 * Certains indicatifs sont partagés (US/CA = 1, RU/KZ = 7) — chaque pays garde
 * son entrée pour l'affichage.
 */
export const COUNTRY_DIAL_CODES: Record<string, string> = {
  AF: "93", ZA: "27", AL: "355", DZ: "213", DE: "49", AD: "376", AO: "244",
  AG: "1268", SA: "966", AR: "54", AM: "374", AU: "61", AT: "43", AZ: "994",
  BS: "1242", BH: "973", BD: "880", BB: "1246", BE: "32", BZ: "501", BJ: "229",
  BT: "975", BY: "375", MM: "95", BO: "591", BA: "387", BW: "267", BR: "55",
  BN: "673", BG: "359", BF: "226", BI: "257", KH: "855", CM: "237", CA: "1",
  CV: "238", CL: "56", CN: "86", CY: "357", CO: "57", KM: "269", CG: "242",
  CD: "243", KR: "82", KP: "850", CR: "506", CI: "225", HR: "385", CU: "53",
  DK: "45", DJ: "253", DM: "1767", EG: "20", AE: "971", EC: "593", ER: "291",
  ES: "34", EE: "372", SZ: "268", US: "1", ET: "251", FJ: "679", FI: "358",
  FR: "33", GA: "241", GM: "220", GE: "995", GH: "233", GR: "30", GD: "1473",
  GT: "502", GN: "224", GQ: "240", GW: "245", GY: "592", HT: "509", HN: "504",
  HU: "36", IN: "91", ID: "62", IQ: "964", IR: "98", IE: "353", IS: "354",
  IL: "972", IT: "39", JM: "1876", JP: "81", JO: "962", KZ: "7", KE: "254",
  KG: "996", KI: "686", KW: "965", LA: "856", LS: "266", LV: "371", LB: "961",
  LR: "231", LY: "218", LI: "423", LT: "370", LU: "352", MK: "389", MG: "261",
  MY: "60", MW: "265", MV: "960", ML: "223", MT: "356", MA: "212", MH: "692",
  MU: "230", MR: "222", MX: "52", FM: "691", MD: "373", MC: "377", MN: "976",
  ME: "382", MZ: "258", NA: "264", NR: "674", NP: "977", NI: "505", NE: "227",
  NG: "234", NO: "47", NZ: "64", OM: "968", UG: "256", UZ: "998", PK: "92",
  PW: "680", PS: "970", PA: "507", PG: "675", PY: "595", NL: "31", PE: "51",
  PH: "63", PL: "48", PT: "351", QA: "974", CF: "236", DO: "1809", CZ: "420",
  RO: "40", GB: "44", RU: "7", RW: "250", KN: "1869", SM: "378", VC: "1784",
  LC: "1758", SB: "677", SV: "503", WS: "685", ST: "239", SN: "221", RS: "381",
  SC: "248", SL: "232", SG: "65", SK: "421", SI: "386", SO: "252", SD: "249",
  SS: "211", LK: "94", SE: "46", CH: "41", SR: "597", SY: "963", TJ: "992",
  TZ: "255", TD: "235", TH: "66", TL: "670", TG: "228", TO: "676", TT: "1868",
  TN: "216", TM: "993", TR: "90", TV: "688", UA: "380", UY: "598", VU: "678",
  VA: "379", VE: "58", VN: "84", YE: "967", ZM: "260", ZW: "263",
}

/**
 * Normalise pour la recherche : minuscule + suppression des accents.
 * "cote" matche "Côte d'Ivoire", "SENEGAL" matche "Sénégal".
 */
export function normalizeCountrySearch(value: string): string {
  return value
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .trim()
}

/** Filtre les pays par recherche insensible aux accents et à la casse. */
export function filterCountries(query: string): Country[] {
  const q = normalizeCountrySearch(query)
  if (!q) return [...ALL_COUNTRIES]
  return ALL_COUNTRIES.filter((c) => normalizeCountrySearch(c.name).includes(q))
}
