// Liste de domaines d'emails jetables / temporaires connus.
// Bloqués à l'inscription pour limiter les abus et garantir un canal de contact valide.
// Source : compilation de listes publiques (disposable-email-domains, etc.) — non exhaustive.

const DISPOSABLE_EMAIL_DOMAINS = new Set<string>([
  "0-mail.com",
  "10minutemail.com",
  "10minutemail.net",
  "20minutemail.com",
  "33mail.com",
  "anonbox.net",
  "anonymbox.com",
  "bltiwd.com",
  "byom.de",
  "deadaddress.com",
  "despam.it",
  "dispostable.com",
  "dropmail.me",
  "e4ward.com",
  "emailondeck.com",
  "emailtemporanea.net",
  "fakeinbox.com",
  "fakemailgenerator.com",
  "fakemail.net",
  "filzmail.com",
  "getairmail.com",
  "getnada.com",
  "guerrillamail.com",
  "guerrillamail.net",
  "guerrillamail.org",
  "guerrillamailblock.com",
  "harakirimail.com",
  "hide.biz.st",
  "incognitomail.com",
  "incognitomail.net",
  "incognitomail.org",
  "inboxalias.com",
  "inboxbear.com",
  "inboxkitten.com",
  "jetable.org",
  "kasmail.com",
  "laoia.com",
  "laoyou.com",
  "laovaa.com",
  "lroid.com",
  "mailcatch.com",
  "maildrop.cc",
  "mailexpire.com",
  "mailforspam.com",
  "mailinator.com",
  "mailinator.net",
  "mailinator2.com",
  "mailmoat.com",
  "mailnesia.com",
  "mailnull.com",
  "mailsac.com",
  "mailtrash.net",
  "mintemail.com",
  "moakt.com",
  "mohmal.com",
  "mvrht.com",
  "mytemp.email",
  "mytrashmail.com",
  "nada.email",
  "no-spam.ws",
  "nobulk.com",
  "noclickemail.com",
  "nomail.xl.cx",
  "nospam.ze.tc",
  "objectmail.com",
  "oneoffemail.com",
  "owlpic.com",
  "pookmail.com",
  "rcpt.at",
  "rmqkr.net",
  "sharklasers.com",
  "shieldedmail.com",
  "shitmail.me",
  "smashmail.de",
  "snakemail.com",
  "spam4.me",
  "spambog.com",
  "spambox.us",
  "spamfree24.com",
  "spamfree24.de",
  "spamfree24.eu",
  "spamfree24.info",
  "spamfree24.net",
  "spamfree24.org",
  "spamgourmet.com",
  "spamhole.com",
  "spamify.com",
  "spaminator.de",
  "spammotel.com",
  "spamthis.co.uk",
  "spamthisplease.com",
  "supermailer.jp",
  "tempail.com",
  "tempemail.biz",
  "tempemail.com",
  "tempemail.net",
  "tempinbox.com",
  "tempmail.de",
  "tempmail.eu",
  "tempmail.io",
  "tempmail.it",
  "tempmail.net",
  "tempmail.us",
  "tempmail2.com",
  "tempmailaddress.com",
  "tempmailer.com",
  "tempmailo.com",
  "tempomail.fr",
  "temporarily.de",
  "temporarioemail.com.br",
  "temporary-email.com",
  "temporaryemail.us",
  "temporaryforwarding.com",
  "temporaryinbox.com",
  "temporarymail.com",
  "temporarymailaddress.com",
  "thankyou2010.com",
  "thisisnotmyrealemail.com",
  "throwam.com",
  "throwawayemailaddresses.com",
  "throwawaymail.com",
  "trashmail.at",
  "trashmail.com",
  "trashmail.de",
  "trashmail.io",
  "trashmail.me",
  "trashmail.net",
  "trashmail.org",
  "trashmail.ws",
  "trashmailer.com",
  "trbvm.com",
  "trillianpro.com",
  "twinmail.de",
  "uggsrock.com",
  "upliftnow.com",
  "veryrealemail.com",
  "vomoto.com",
  "vpn.st",
  "wegwerfadresse.de",
  "wegwerfemail.com",
  "wegwerfemail.de",
  "wegwerfmail.de",
  "wegwerfmail.info",
  "wegwerfmail.net",
  "wegwerfmail.org",
  "wh4f.org",
  "whyspam.me",
  "willhackforfood.biz",
  "wilemail.com",
  "writeme.us",
  "wronghead.com",
  "wuzup.net",
  "wuzupmail.net",
  "yapped.net",
  "yep.it",
  "yopmail.com",
  "yopmail.fr",
  "yopmail.net",
  "yourdomain.com",
  "yuurok.com",
  "zehnminutenmail.de",
  "zoaxe.com",
  "zoemail.com",
  "zoemail.net",
  "zoemail.org",
])

// Domaines de test / RFC reserved / placeholder — à bloquer aussi pour les inscriptions publiques.
const FAKE_EMAIL_DOMAINS = new Set<string>([
  "test.com",
  "test.fr",
  "test.io",
  "test.net",
  "test.org",
  "tests.com",
  "exemple.com",
  "exemple.fr",
  "example.com", // RFC 2606
  "example.org",
  "example.net",
  "example.fr",
  "example.io",
  "fake.com",
  "fake.fr",
  "faux.com",
  "demo.com",
  "domain.com",
  "email.com",
  "mail.com",
  "abc.com",
  "xyz.com",
  "asdf.com",
  "qwerty.com",
  "azerty.com",
  "aaa.com",
  "bbb.com",
  "ccc.com",
  "lol.com",
  "nope.com",
  "noemail.com",
  "no-email.com",
  "spam.com",
  "spamfree.com",
  "invalid.com",
  "localhost",
  "localhost.com",
  "yourcompany.com",
  "yourdomain.fr",
  "example.test",
  "test.test",
])

// Patterns d'usernames manifestement bidons (avant @)
const FAKE_USERNAME_PATTERNS = [
  /^test\d*$/i,
  /^tests?\d*$/i,
  /^demo\d*$/i,
  /^fake\d*$/i,
  /^faux\d*$/i,
  /^essai\d*$/i,
  /^abc\d*$/i,
  /^xyz\d*$/i,
  /^aaa+\d*$/i,
  /^asdf+\d*$/i,
  /^qwerty\d*$/i,
  /^azerty\d*$/i,
  /^lol\d*$/i,
  /^nope\d*$/i,
  /^spam\d*$/i,
  /^toto\d*$/i,
  /^titi\d*$/i,
  /^tata\d*$/i,
  /^a$/i,
  /^.{1,2}$/, // 1-2 caractères seulement
]

/**
 * Vérifie si un email utilise un domaine jetable / temporaire connu.
 */
export function isDisposableEmail(email: string): boolean {
  const at = email.lastIndexOf("@")
  if (at === -1) return false
  const domain = email.slice(at + 1).trim().toLowerCase()
  if (!domain) return false
  return DISPOSABLE_EMAIL_DOMAINS.has(domain)
}

/**
 * Vérifie si un email semble être un email de test / placeholder / bidon.
 * Combine domaines de test connus + patterns d'username manifestement faux.
 */
export function isFakeEmail(email: string): boolean {
  const at = email.lastIndexOf("@")
  if (at === -1) return true
  const username = email.slice(0, at).trim().toLowerCase()
  const domain = email.slice(at + 1).trim().toLowerCase()
  if (!username || !domain) return true
  if (FAKE_EMAIL_DOMAINS.has(domain)) return true
  if (FAKE_USERNAME_PATTERNS.some((re) => re.test(username))) return true
  return false
}

/**
 * True si l'email est jetable OU bidon. Utilisé pour bloquer les inscriptions.
 */
export function isBlockedEmail(email: string): boolean {
  return isDisposableEmail(email) || isFakeEmail(email)
}

