import type { ContentItem } from "@/components/dashboard/content-card"

// Images génériques Unsplash pour les campagnes
const campaignImages = {
  telecoms: [
    "https://images.unsplash.com/photo-1556740758-90de374c12ad?w=800&h=450&fit=crop",
    "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&h=450&fit=crop",
    "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&h=450&fit=crop",
  ],
  finance: [
    "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800&h=450&fit=crop",
    "https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=800&h=450&fit=crop",
    "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=450&fit=crop",
  ],
  fmcg: [
    "https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&h=450&fit=crop",
    "https://images.unsplash.com/photo-1534723452862-4c874018d66d?w=800&h=450&fit=crop",
    "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&h=450&fit=crop",
  ],
  ecommerce: [
    "https://images.unsplash.com/photo-1556742111-a301076d9d18?w=800&h=450&fit=crop",
    "https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=800&h=450&fit=crop",
    "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&h=450&fit=crop",
  ],
  tech: [
    "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&h=450&fit=crop",
    "https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?w=800&h=450&fit=crop",
    "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&h=450&fit=crop",
  ],
  energie: [
    "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=800&h=450&fit=crop",
    "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800&h=450&fit=crop",
  ],
  industrie: [
    "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&h=450&fit=crop",
    "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=800&h=450&fit=crop",
  ],
  default: [
    "https://images.unsplash.com/photo-1557804506-669a67965ba0?w=800&h=450&fit=crop",
    "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=450&fit=crop",
    "https://images.unsplash.com/photo-1551434678-e076c223a692?w=800&h=450&fit=crop",
  ]
}

const getSectorKey = (sector: string) => {
  return sector.toLowerCase().includes("telecom") ? "telecoms"
    : sector.toLowerCase().includes("banque") || sector.toLowerCase().includes("finance") ? "finance"
    : sector.toLowerCase().includes("fmcg") ? "fmcg"
    : sector.toLowerCase().includes("commerce") ? "ecommerce"
    : sector.toLowerCase().includes("tech") ? "tech"
    : sector.toLowerCase().includes("energie") ? "energie"
    : sector.toLowerCase().includes("industrie") ? "industrie"
    : "default"
}

const getRandomImage = (sector: string, index: number) => {
  const images = campaignImages[getSectorKey(sector) as keyof typeof campaignImages]
  return images[index % images.length]
}

const getExtraImages = (sector: string, mainIndex: number) => {
  const sectorKey = getSectorKey(sector) as keyof typeof campaignImages
  const images = campaignImages[sectorKey]
  // Return the other images from the same sector (excluding the main one)
  return images.filter((_, i) => i !== mainIndex % images.length)
}

export const sampleContent: ContentItem[] = [
  {
    id: "1",
    title: "MTN Ghana - Mobile Money Campaign",
    description: "Campagne virale pour promouvoir les services de transfert d'argent mobile avec des influenceurs locaux.",
    imageUrl: getRandomImage("Telecoms", 0),
    images: getExtraImages("Telecoms", 0),
    platform: "Facebook",
    country: "Côte d'Ivoire",
    sector: "Telecoms",
    format: "Vidéos Ad",
    tags: ["Fintech", "Humour", "Viral"],
    date: "Jan 2024",
    brand: "MTN",
    agency: "Ogilvy Africa",
    year: 2024,
    isVideo: true,
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ"
  },
  {
    id: "2",
    title: "Orange CI - Fete de la Musique",
    description: "Activation musicale avec des artistes locaux pour celebrer la fete de la musique et renforcer le lien avec la jeunesse.",
    imageUrl: getRandomImage("Telecoms", 1),
    images: getExtraImages("Telecoms", 1),
    platform: "Instagram",
    country: "Côte d'Ivoire",
    sector: "Telecoms",
    format: "Story",
    tags: ["Musique", "Culture", "Evenement"],
    date: "Juin 2024",
    brand: "Orange",
    agency: "McCann Abidjan",
    year: 2024,
    isVideo: true,
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ"
  },
  {
    id: "3",
    title: "Jumia Nigeria - Black Friday Madness",
    description: "Campagne 360 pour le Black Friday avec countdown, influenceurs et offres exclusives sur l'app.",
    imageUrl: getRandomImage("E-commerce", 2),
    images: getExtraImages("E-commerce", 2),
    platform: "TikTok",
    country: "Bénin",
    sector: "E-commerce",
    format: "Carrousel Ad",
    tags: ["Promo", "FOMO", "Saisonnier"],
    date: "Nov 2024",
    brand: "Jumia",
    agency: "DDB Lagos",
    year: 2024,
    isVideo: true,
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ"
  },
  {
    id: "4",
    title: "Wave Senegal - Envoi d'argent simplifie",
    description: "Serie de temoignages clients montrant la simplicite des transferts d'argent via Wave.",
    imageUrl: getRandomImage("Banque/Finance", 3),
    images: getExtraImages("Banque/Finance", 3),
    platform: "YouTube",
    country: "Sénégal",
    sector: "Banque/Finance",
    format: "Vidéos Ad",
    tags: ["Temoignage", "Simplicite", "Trust"],
    date: "Dec 2024",
    brand: "Wave",
    agency: "TBWA Dakar",
    year: 2024,
    isVideo: true,
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ"
  },
  {
    id: "5",
    title: "Dangote Cement - Building Africa",
    description: "Campagne corporate mettant en avant la contribution de Dangote a la construction du continent.",
    imageUrl: getRandomImage("Industrie", 4),
    images: getExtraImages("Industrie", 4),
    platform: "LinkedIn",
    country: "Burkina Faso",
    sector: "Industrie",
    format: "Image",
    tags: ["Corporate", "RSE", "Brand"],
    date: "Jan 2024",
    brand: "Dangote",
    agency: "SO&U",
    year: 2024,
    isVideo: false
  },
  {
    id: "6",
    title: "Societe Generale CI - Compte Jeune",
    description: "Lancement du compte bancaire jeune avec une campagne ciblee sur les etudiants et jeunes actifs.",
    imageUrl: getRandomImage("Banque/Finance", 5),
    images: getExtraImages("Banque/Finance", 5),
    platform: "Instagram",
    country: "Côte d'Ivoire",
    sector: "Banque/Finance",
    format: "Carrousel",
    tags: ["Jeunesse", "Lancement", "Digital"],
    date: "Sep 2024",
    brand: "Société Générale",
    agency: "Voodoo Agency",
    year: 2024,
    isVideo: false
  },
  {
    id: "7",
    title: "Coca-Cola Africa - Share a Coke",
    description: "Adaptation africaine de la campagne Share a Coke avec des prenoms locaux populaires.",
    imageUrl: getRandomImage("FMCG", 6),
    images: getExtraImages("FMCG", 6),
    platform: "Facebook",
    country: "Togo",
    sector: "FMCG",
    format: "Image Ad",
    tags: ["Personnalisation", "Viral", "UGC"],
    date: "Oct 2024",
    brand: "Coca-Cola",
    agency: "FCB Africa",
    year: 2024,
    isVideo: false
  },
  {
    id: "8",
    title: "Safaricom Kenya - M-Pesa 20 ans",
    description: "Celebration des 20 ans de M-Pesa avec des stories emotionnelles sur l'impact du service.",
    imageUrl: getRandomImage("Telecoms", 7),
    images: getExtraImages("Telecoms", 7),
    platform: "YouTube",
    country: "Guinée",
    sector: "Telecoms",
    format: "Vidéo",
    tags: ["Anniversaire", "Storytelling", "Emotion"],
    date: "Mars 2024",
    brand: "Safaricom",
    agency: "Scanad",
    year: 2024,
    isVideo: true,
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ"
  },
  {
    id: "9",
    title: "Airtel Nigeria - Data Bundle Promo",
    description: "Promotion agressive sur les forfaits data avec un mecanisme de parrainage viral.",
    imageUrl: getRandomImage("Telecoms", 8),
    images: getExtraImages("Telecoms", 8),
    platform: "Twitter/X",
    country: "Bénin",
    sector: "Telecoms",
    format: "Photo",
    tags: ["Promo", "Parrainage", "Urgence"],
    date: "Fev 2024",
    brand: "Airtel",
    agency: "Noah's Ark Lagos",
    year: 2024,
    isVideo: false
  },
  {
    id: "10",
    title: "Nestle Maggi - Recettes Africaines",
    description: "Serie de videos courtes avec des recettes traditionnelles africaines revisitees.",
    imageUrl: getRandomImage("FMCG", 9),
    images: getExtraImages("FMCG", 9),
    platform: "TikTok",
    country: "Sénégal",
    sector: "FMCG",
    format: "Story",
    tags: ["Food", "Culture", "Tutorial"],
    date: "Avril 2024",
    brand: "Nestlé Maggi",
    agency: "Publicis Dakar",
    year: 2024,
    isVideo: true,
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ"
  },
  {
    id: "11",
    title: "Total Energies - Station Solaire",
    description: "Campagne RSE sur l'installation de stations solaires dans les zones rurales.",
    imageUrl: getRandomImage("Energie", 10),
    images: getExtraImages("Energie", 10),
    platform: "LinkedIn",
    country: "Côte d'Ivoire",
    sector: "Energie",
    format: "Image",
    tags: ["RSE", "Environnement", "Innovation"],
    date: "Mai 2024",
    isVideo: false
  },
  {
    id: "12",
    title: "UBA Africa - Pan-African Banking",
    description: "Campagne institutionnelle positionnant UBA comme la banque panafricaine de reference.",
    imageUrl: getRandomImage("Banque/Finance", 11),
    images: getExtraImages("Banque/Finance", 11),
    platform: "YouTube",
    country: "Burkina Faso",
    sector: "Banque/Finance",
    format: "Vidéos Ad",
    tags: ["Corporate", "Pan-African", "Trust"],
    date: "Juil 2024",
    brand: "UBA",
    agency: "Insight Publicis",
    year: 2024,
    isVideo: true,
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ"
  },
  {
    id: "13",
    title: "Glovo Togo - Livraison Express",
    description: "Challenge TikTok montrant la rapidite de livraison Glovo avec des influenceurs locaux.",
    imageUrl: getRandomImage("E-commerce", 12),
    images: getExtraImages("E-commerce", 12),
    platform: "TikTok",
    country: "Togo",
    sector: "E-commerce",
    format: "Story",
    tags: ["Challenge", "Influenceur", "Humour"],
    date: "Aout 2024",
    brand: "Glovo",
    agency: "Tribal DDB",
    year: 2024,
    isVideo: true,
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ"
  },
  {
    id: "14",
    title: "Moov Africa - Forfait Illimite",
    description: "Lancement du forfait illimite avec une campagne teaser mystere suivie d'une revelation.",
    imageUrl: getRandomImage("Telecoms", 13),
    images: getExtraImages("Telecoms", 13),
    platform: "Instagram",
    country: "Côte d'Ivoire",
    sector: "Telecoms",
    format: "Carrousel",
    tags: ["Teaser", "Lancement", "Suspense"],
    date: "Sep 2024",
    brand: "Moov Africa",
    agency: "McCann Abidjan",
    year: 2024,
    isVideo: false
  },
  {
    id: "15",
    title: "Ecobank - Digital Banking",
    description: "Tutoriel video sur l'utilisation de l'app Ecobank pour les operations bancaires quotidiennes.",
    imageUrl: getRandomImage("Banque/Finance", 14),
    images: getExtraImages("Banque/Finance", 14),
    platform: "Facebook",
    country: "Guinée",
    sector: "Banque/Finance",
    format: "Vidéos Ad",
    tags: ["Tutorial", "Digital", "Education"],
    date: "Oct 2024",
    brand: "Ecobank",
    agency: "Exp Agency",
    year: 2024,
    isVideo: true,
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ"
  },
  // Contenu supplémentaire pour simuler une grande base de données
  {
    id: "16",
    title: "Nescafé Afrique - Morning Routine",
    description: "Série de mini-documentaires sur les routines matinales de créateurs africains avec Nescafé.",
    imageUrl: getRandomImage("FMCG", 15),
    images: getExtraImages("FMCG", 15),
    platform: "YouTube",
    country: "Côte d'Ivoire",
    sector: "FMCG",
    format: "Vidéo",
    tags: ["Lifestyle", "Storytelling", "Morning"],
    date: "Nov 2024",
    brand: "Nescafé",
    agency: "Publicis Africa",
    year: 2024,
    isVideo: true,
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ"
  },
  {
    id: "17",
    title: "Vodafone Sénégal - 5G Launch",
    description: "Campagne de lancement de la 5G au Sénégal avec des démonstrations technologiques impressionnantes.",
    imageUrl: getRandomImage("Telecoms", 16),
    images: getExtraImages("Telecoms", 16),
    platform: "YouTube",
    country: "Sénégal",
    sector: "Telecoms",
    format: "Carrousel Ad",
    tags: ["Tech", "Innovation", "Lancement"],
    date: "Dec 2024",
    brand: "Vodafone",
    agency: "TBWA Dakar",
    year: 2024,
    isVideo: true,
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ"
  },
  {
    id: "18",
    title: "Guinness Nigeria - Made of Black",
    description: "Célébration de la culture africaine et de l'identité noire à travers des portraits artistiques.",
    imageUrl: getRandomImage("FMCG", 17),
    images: getExtraImages("FMCG", 17),
    platform: "Instagram",
    country: "Bénin",
    sector: "FMCG",
    format: "Carrousel",
    tags: ["Culture", "Identité", "Art"],
    date: "Oct 2024",
    brand: "Guinness",
    agency: "BBDO Lagos",
    year: 2024,
    isVideo: false
  },
  {
    id: "19",
    title: "FirstBank Nigeria - 130 Years",
    description: "Campagne anniversaire célébrant 130 ans de présence bancaire au Nigeria.",
    imageUrl: getRandomImage("Banque/Finance", 18),
    images: getExtraImages("Banque/Finance", 18),
    platform: "LinkedIn",
    country: "Burkina Faso",
    sector: "Banque/Finance",
    format: "Vidéos Ad",
    tags: ["Anniversaire", "Heritage", "Trust"],
    date: "Jan 2024",
    brand: "FirstBank",
    agency: "SO&U",
    year: 2024,
    isVideo: true,
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ"
  },
  {
    id: "20",
    title: "Senelec - Energie Verte",
    description: "Sensibilisation aux énergies renouvelables et aux économies d'énergie au Sénégal.",
    imageUrl: getRandomImage("Energie", 19),
    images: getExtraImages("Energie", 19),
    platform: "Facebook",
    country: "Sénégal",
    sector: "Energie",
    format: "Image",
    tags: ["Environnement", "RSE", "Education"],
    date: "Mars 2024",
    brand: "Senelec",
    agency: "Impact BBDO Dakar",
    year: 2024,
    isVideo: false
  }
]
