-- Table des temps forts (Coupe du monde, Ramadan, Black Friday…)
-- Remplace le tableau statique de lib/temps-forts.ts par des données pilotables depuis l'admin.

CREATE TABLE IF NOT EXISTS temps_forts (
  id text PRIMARY KEY,
  slug text NOT NULL UNIQUE,
  title text NOT NULL,
  short_title text,
  description text NOT NULL DEFAULT '',
  image_url text NOT NULL DEFAULT '',
  hero_image_url text,
  date_activation date NOT NULL,
  event_date date NOT NULL,
  end_date date,
  is_active boolean NOT NULL DEFAULT true,
  category text NOT NULL DEFAULT '',
  campaign_count integer NOT NULL DEFAULT 0,
  tags text[] NOT NULL DEFAULT '{}'::text[],
  sectors text[] NOT NULL DEFAULT '{}'::text[],
  axes text[] NOT NULL DEFAULT '{}'::text[],
  countries text[] NOT NULL DEFAULT '{}'::text[],
  formats text[] NOT NULL DEFAULT '{}'::text[],
  platforms text[] NOT NULL DEFAULT '{}'::text[],
  featured boolean NOT NULL DEFAULT false,
  popup_enabled boolean NOT NULL DEFAULT false,
  cta_label text,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS temps_forts_slug_idx ON temps_forts (slug);
CREATE INDEX IF NOT EXISTS temps_forts_is_active_idx ON temps_forts (is_active);
CREATE INDEX IF NOT EXISTS temps_forts_event_date_idx ON temps_forts (event_date);

-- Seed initial : transcrit le contenu actuel de lib/temps-forts.ts.
INSERT INTO temps_forts (
  id, slug, title, short_title, description, image_url, hero_image_url,
  date_activation, event_date, end_date, is_active, category, campaign_count,
  tags, sectors, axes, countries, formats, platforms, featured, popup_enabled, cta_label, sort_order
) VALUES
  ('tf-world-cup-2026','coupe-du-monde-2026','La Coupe du monde arrive !','Coupe du monde',
   'Découvrez les campagnes sportives qui transforment la ferveur football en activation de marque.',
   '/temps-forts/coupe-du-monde.png','/temps-forts/coupe-du-monde.png',
   '2026-04-01','2026-06-11','2026-07-19',true,'Sport',52,
   ARRAY['Football','Fan engagement','Sponsoring','Émotion collective'],
   ARRAY['Boisson','Télécom','Banque','FMCG'],
   ARRAY['Fierté nationale','Communauté','Performance'],
   ARRAY['Bénin','Cameroun','Côte d''Ivoire','Sénégal'],
   ARRAY['Vidéo','Image','OOH'],
   ARRAY['Facebook','Instagram','TikTok','YouTube'],
   true,true,'Explorer la Coupe du monde',10),
  ('tf-mothers-day-2026','fete-des-meres-2026','Fête des mères',NULL,
   'Des idées de campagnes tendres, utiles et mémorables pour parler famille sans tomber dans le cliché.',
   '/temps-forts/fete-des-meres.png',NULL,
   '2026-04-15','2026-05-31',NULL,true,'Famille',34,
   ARRAY['Famille','Cadeau','Émotion','Retail'],
   ARRAY['E-commerce','FMCG','Assurance','Beauté'],
   ARRAY['Gratitude','Attention','Transmission'],
   ARRAY['Bénin','Cameroun','Côte d''Ivoire'],
   ARRAY['Image','Vidéo'],
   ARRAY['Facebook','Instagram','TikTok'],
   true,false,NULL,20),
  ('tf-music-day-2026','fete-de-la-musique-2026','Fête de la musique',NULL,
   'Inspirez-vous des marques qui font vibrer leur communauté autour de playlists, live et contenus créateurs.',
   '/temps-forts/fete-de-la-musique.png',NULL,
   '2026-04-20','2026-06-21',NULL,true,'Culture',22,
   ARRAY['Musique','Culture','Créateurs','Live'],
   ARRAY['Télécom','Boisson','Culture'],
   ARRAY['Divertissement','Communauté','Expression'],
   ARRAY['Bénin','Cameroun','Sénégal'],
   ARRAY['Vidéo','Reels','Carrousel'],
   ARRAY['Instagram','TikTok','YouTube'],
   true,false,NULL,30),
  ('tf-ramadan-2026','ramadan-2026','Ramadan',NULL,
   'Repérez les mécaniques de contenu qui associent utilité, générosité et respect du moment.',
   '/temps-forts/ramadan.png',NULL,
   '2026-01-15','2026-02-18','2026-03-19',true,'Religion',47,
   ARRAY['Ramadan','Solidarité','Famille','Fidélité'],
   ARRAY['FMCG','Banque','Télécom','Retail'],
   ARRAY['Générosité','Utilité','Communauté'],
   ARRAY['Cameroun','Côte d''Ivoire','Sénégal'],
   ARRAY['Vidéo','Image','Stories'],
   ARRAY['Facebook','Instagram','WhatsApp'],
   false,false,NULL,40),
  ('tf-back-to-school-2026','rentree-scolaire-2026','Rentrée scolaire',NULL,
   'Des campagnes pratiques pour accompagner les familles, les élèves et les commerces de proximité.',
   '/temps-forts/rentree-scolaire.png',NULL,
   '2026-07-15','2026-09-01',NULL,true,'Éducation',28,
   ARRAY['Éducation','Famille','Promo','Préparation'],
   ARRAY['Banque','Retail','Assurance','Télécom'],
   ARRAY['Préparation','Économie','Confiance'],
   ARRAY['Bénin','Cameroun','Côte d''Ivoire'],
   ARRAY['Image','Carrousel','OOH'],
   ARRAY['Facebook','Instagram'],
   false,false,NULL,50),
  ('tf-black-friday-2026','black-friday-2026','Black Friday',NULL,
   'Analysez les offres, urgences et mécaniques e-commerce qui créent du trafic sans dégrader la marque.',
   '/temps-forts/black-friday.png',NULL,
   '2026-10-01','2026-11-27',NULL,true,'Commerce',41,
   ARRAY['Commerce','Promotion','E-commerce','Urgence'],
   ARRAY['E-commerce','Retail','Tech','Télécom'],
   ARRAY['Offre','Rareté','Conversion'],
   ARRAY['Bénin','Cameroun','Côte d''Ivoire','Sénégal'],
   ARRAY['Image','Vidéo','Landing page'],
   ARRAY['Facebook','Instagram','Google'],
   false,false,NULL,60),
  ('tf-valentine-2026','saint-valentin-2026','Saint-Valentin',NULL,
   'Explorez les prises de parole amour, cadeau et attention, des plus premium aux plus conversationnelles.',
   '/temps-forts/saint-valentin.png',NULL,
   '2026-01-10','2026-02-14',NULL,true,'Love',31,
   ARRAY['Love','Cadeau','Couple','Retail'],
   ARRAY['FMCG','Beauté','E-commerce','Télécom'],
   ARRAY['Attention','Humour','Émotion'],
   ARRAY['Cameroun','Côte d''Ivoire','Sénégal'],
   ARRAY['Image','Reels','Stories'],
   ARRAY['Instagram','TikTok','Facebook'],
   false,false,NULL,70),
  ('tf-afcon-2025','can-2025','CAN 2025',NULL,
   'Retrouvez les activations football africaines autour des équipes, supporters et marques partenaires.',
   '/temps-forts/can-2025.png',NULL,
   '2025-10-01','2025-12-21','2026-01-18',true,'Sport',39,
   ARRAY['Football','Afrique','Supporters','Sponsoring'],
   ARRAY['Boisson','Banque','Télécom'],
   ARRAY['Fierté','Supporters','Victoire'],
   ARRAY['Bénin','Cameroun','Côte d''Ivoire','Sénégal'],
   ARRAY['Vidéo','Image','OOH'],
   ARRAY['Facebook','Instagram','YouTube'],
   false,false,NULL,80),
  ('tf-christmas-2026','noel-2026','Noël',NULL,
   'Des campagnes cadeaux, famille et générosité pour préparer les prises de parole de fin d''année.',
   '/temps-forts/noel.png',NULL,
   '2026-11-01','2026-12-25',NULL,true,'Fête',45,
   ARRAY['Noël','Cadeau','Famille','Générosité'],
   ARRAY['Retail','FMCG','E-commerce','Banque'],
   ARRAY['Cadeau','Famille','Générosité'],
   ARRAY['Bénin','Cameroun','Côte d''Ivoire'],
   ARRAY['Image','Vidéo','Carrousel'],
   ARRAY['Facebook','Instagram','TikTok'],
   false,false,NULL,90)
ON CONFLICT (id) DO NOTHING;
